### 1. Khai báo thư viện cần dùng

In [2]:
import pandas as pd
import numpy as np

### 2. Tạo biến một danh sách tuổi

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [3]:
# Hãy chia chúng thành các nhóm từ 18 đến 25, 26 đến 35, 36 đến 60 và cuối cùng là 61 trở lên. 
# định nghĩa khoảng giá trị các nhóm
bins = [18, 25, 35, 60, 100]

In [5]:
# thực hiện rời rạc hóa
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [6]:
# lấy ra index của nhóm tương ứng với các phần tử
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [7]:
# lấy ra các nhóm
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [8]:
# thống kê số lượng phần tử ở mỗi nhóm
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [9]:
# Thay đổi phía bị đóng bằng cách truyền vào tham số right = False:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [10]:
# danh sách nhãn
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

### 3. sinh dữ liệu ngẫu nhiên gồm 20 phần tử

In [14]:
data = np.random.rand(20)
data

array([0.41627681, 0.34685249, 0.40887122, 0.03308323, 0.35195316,
       0.97703703, 0.76072981, 0.34109709, 0.61317987, 0.82424393,
       0.394294  , 0.86131771, 0.77555126, 0.18810739, 0.23636166,
       0.22427513, 0.81554303, 0.71637735, 0.40327716, 0.01886847])

In [15]:
cut_data = pd.cut(data, 4, precision=2) # precision=2 giới hạn độ chính xác ở 2 chữ số thập phân
cut_data

[(0.26, 0.5], (0.26, 0.5], (0.26, 0.5], (0.018, 0.26], (0.26, 0.5], ..., (0.018, 0.26], (0.74, 0.98], (0.5, 0.74], (0.26, 0.5], (0.018, 0.26]]
Length: 20
Categories (4, interval[float64, right]): [(0.018, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [17]:
# lấy ra các nhóm
cut_data.categories

IntervalIndex([(0.018, 0.26], (0.26, 0.5], (0.5, 0.74], (0.74, 0.98]], dtype='interval[float64, right]')

In [19]:
# thống kê số lượng phần tử ở mỗi nhóm
pd.value_counts(cut_data)

(0.26, 0.5]      7
(0.74, 0.98]     6
(0.018, 0.26]    5
(0.5, 0.74]      2
dtype: int64

### 4. Sinh ngẫu nhiễn 1000 điểm dữ liệu

In [22]:
data = np.random.randn(1000)
data

array([ 5.80009042e-01,  4.87157423e-01, -3.08315497e-01, -2.41506272e-01,
       -1.14844416e+00,  5.39813241e-01,  4.92016702e-01, -1.24959747e+00,
       -1.93237442e-01, -8.99240793e-01, -2.28638380e-01, -3.22706516e-01,
        3.81899116e-01, -2.71506344e-01, -8.98529175e-01, -1.04288967e+00,
        6.82793293e-01, -1.46300676e+00,  1.22976822e+00, -4.33173756e-02,
       -1.30782793e+00,  3.01559053e-01,  7.25824071e-01, -2.90994946e-01,
        4.66448625e-01, -2.54048659e-01,  1.17335364e+00, -9.41027591e-02,
       -8.18322961e-02,  3.17183941e-01, -3.45903182e-01, -6.50293162e-01,
        2.81643188e-01,  1.44597763e-02, -9.81403071e-03, -1.63021387e+00,
        3.14957566e-02, -8.93632715e-01, -1.74643613e-01,  1.12259220e-01,
        4.08177923e-01,  1.93238260e+00,  3.50474253e-01, -4.45780925e-01,
       -1.39250531e+00,  4.35015418e-01, -5.30067197e-01, -1.36726361e+00,
       -4.94431409e-01,  1.44224247e+00,  4.44643294e-01, -3.57291407e+00,
       -1.24545668e-01, -

In [23]:
# qcut sử dụng các lượng tử mẫu thay thế, nên chúng sẽ nhận được các nhóm có kích thước gần bằng nhau
# thực hiện hàm qcut trên dữ liệu vừa sinh ra
cats = pd.qcut(data, 4)
cats

[(0.0173, 0.627], (0.0173, 0.627], (-0.619, 0.0173], (-0.619, 0.0173], (-3.574, -0.619], ..., (0.0173, 0.627], (-3.574, -0.619], (-3.574, -0.619], (0.627, 4.113], (0.627, 4.113]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.574, -0.619] < (-0.619, 0.0173] < (0.0173, 0.627] < (0.627, 4.113]]

In [24]:
cats.categories

IntervalIndex([(-3.574, -0.619], (-0.619, 0.0173], (0.0173, 0.627], (0.627, 4.113]], dtype='interval[float64, right]')

In [25]:
#thống kê số lượng phần tử
pd.value_counts(cats)

(-3.574, -0.619]    250
(-0.619, 0.0173]    250
(0.0173, 0.627]     250
(0.627, 4.113]      250
dtype: int64

In [26]:
# chuyển các lượng tử của riêng mình (các số từ 0 đến 1):
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0173, 1.24], (0.0173, 1.24], (-1.256, 0.0173], (-1.256, 0.0173], (-1.256, 0.0173], ..., (0.0173, 1.24], (-1.256, 0.0173], (-3.574, -1.256], (1.24, 4.113], (0.0173, 1.24]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.574, -1.256] < (-1.256, 0.0173] < (0.0173, 1.24] < (1.24, 4.113]]